url: https://ammimarketic.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: AMMI MarkeTIC
email: abdoulayedoucoure.ammi@gmail.com
description: "VOTRE AGENCE DE MARKETING CONVERSATIONNEL avec une équipe d’experts spécialisée dans le web et l’IA. Obtenez une présence digitale complète - Simple et Rapide ! Nos délais de livraison d'une semaine par étape peuvent être accélérés à votre demande."


# Team names, titles and social links
people:
- name: WELTARE Strategies
  pic: 1
  position: Conseil en strategie
  social:
    - title: twitter
      url: https://twitter.com/neohack22
    - title: facebook
      url: https://www.facebook.com/ethercourt
    - title: linkedin
      url: https://www.linkedin.com/company/27132274/admin/products/ethercourt-les-relations-investisseurs-assist%C3%A9es-par-lintelligence-artificielle/

- name: Ethercourt Machine Learning
  pic: 2
  position: Conseil en IA
  social:
    - title: twitter
      url: https://twitter.com/ethercourt
    - title: facebook
      url: https://www.facebook.com/ethercourt/
    - title: linkedin
      url: https://www.linkedin.com/company/ethercourt/

- name: innovatics
  pic: 0
  position: Création de contenu
  social:
    - title: medium
      url: https://medium.com/innovatics
    - title: facebook
      url: https://m.facebook.com/p/Innovatics-100079875672329/
    - title: linkedin
      url: https://www.linkedin.com/showcase/innovatics-ml/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/AmmiMarketic
  - title: facebook
    url: https://www.facebook.com/ammimarketic
  - title: linkedin
    url: https://www.linkedin.com/showcase/ammi-marketic
  - title: github
    url:  https://github.com/AMMIMarkeTIC
  

# Postal address (add as many lines as necessary)
address:
  - line: BKO
  - line: PAR

# Build settings
markdown: kramdown
permalink: pretty
